printing version added to workflow step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,3 +1,26 @@
+# name: ci
+
+# on:
+#   pull_request:
+#     branches: [main]
+
+# jobs:
+#   tests:
+#     name: Tests
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Check out code
+#         uses: actions/checkout@v4
+
+#       - name: Set up Go
+#         uses: actions/setup-go@v5
+#         with:
+#           go-version: "1.25.1"
+
+#       - name: Force Failure
+#         run: (exit 1)
+
 name: ci
 
 on:
@@ -17,6 +40,10 @@ jobs:
         uses: actions/setup-go@v5
         with:
           go-version: "1.25.1"
+      
 
-      - name: Force Failure
-        run: (exit 1)
+      - name: Version Printing
+        run: |
+            echo "Current Go versio is: "
+            go version
+       
